### ISSUE TITLE
DESCRIPTION: Missing package dependencies

### ISSUE THREAD

**Issue by HenrikBengtsson** [SRHilz/GliomaAtlas3D#1]
Congrats to the R package.  I'm not sure exactly how you build and test it.  Personally, I use run:
```sh
$ R CMD build GliomaAtlas3D
$ R CMD check --as-cran GliomaAtlas3D_0.0.0.tar.gz
```
at the command line, but you can also do:
```r
> devtools::check()
```
from within R.  If you do, you'll get the following error:
```
E  checking package dependencies (4s)
   Namespace dependencies not required:
     'RColorBrewer', 'gtools', 'misc3d', 'rgl', 'shiny', 'shinythemes'
   
   See section 'The DESCRIPTION file' in the 'Writing R Extensions'
   manual.
```

All packages that your package `import()` in the `NAMESPACE` need to be listed in a:
`Imports: ...
```
fields of `DESCRIPTION`.

You want to get the package to a stage where `devtools::check()` returns all OK.

**Comment by SRHilz** [comment]
Thanks (and thank you for your email, too!)! I fixed this issue, and then reran check (had to specifically use the following to keep it from getting hung on my examples: 

`
check(args="--no-examples")
`
 While it did give me some helpful nots and warnings of things I can do to further improve the code at some point, this time no errors. Are we now ready to move on to the PR?

<img width="309" alt="Screen Shot 2020-04-02 at 10 32 32 AM" src="https://user-images.githubusercontent.com/5839184/78280122-6f247780-74cd-11ea-9496-dc79b2fdc2dc.png">

**Comment by HenrikBengtsson** [comment]
> ```
> check(args="--no-examples")
> ```

We need to be able to run a plain `devtools::check()`.  Wrap you slow/long-running example code in:
```
\donttest{
...
}
```
That will tell `R CMD check` to skip such example code.

What are the `3 warnings`?  They might be essential for being able to run on GitHub Actions.

**Comment by SRHilz** [comment]
Thanks, that worked and kept it from getting stuck. Now I have 4 warnings (1 I think is a group of them), here they are:


<img width="318" alt="Screen Shot 2020-04-02 at 11 14 27 AM" src="https://user-images.githubusercontent.com/5839184/78283954-7484c080-74d3-11ea-81ec-bb81014084e5.png">


<img width="575" alt="Screen Shot 2020-04-02 at 11 14 37 AM" src="https://user-images.githubusercontent.com/5839184/78283986-80708280-74d3-11ea-8be6-c080444128b6.png">

<img width="579" alt="Screen Shot 2020-04-02 at 11 14 51 AM" src="https://user-images.githubusercontent.com/5839184/78283999-86666380-74d3-11ea-91dd-c5b4566c8f59.png">

<img width="537" alt="Screen Shot 2020-04-02 at 11 15 05 AM" src="https://user-images.githubusercontent.com/5839184/78284004-8a928100-74d3-11ea-9273-064eb0ab8676.png">

**Comment by HenrikBengtsson** [comment]
Do you mind reposting using plain text so I can cut'n'paste in my comments?

**Comment by SRHilz** [comment]
```
W  checking R files for non-ASCII characters ...
   Found the following file with non-ASCII characters:
     loadAboutTab.R
   Portable packages must use only ASCII characters in their R code,
   except perhaps in comments.
   Use \uxxxx escapes for other characters.

W  checking Rd files ...
   checkRd: (7) launchApp.Rd:12: Tag \donttest not recognized
   checkRd: (7) plot3Dmodel.Rd:15-16: Tag \donttest not recognized

W  checking Rd \usage sections ...
   Undocumented arguments in documentation object 'getDataValues'
     ‘tumor’ ‘tumorDatasetsPath’
   Documented arguments not in \usage in documentation object 'getDataValues':
     ‘sf’
   
   Undocumented arguments in documentation object 'plot3Dmodel'
     ‘tumorModelsPath’
   
   Functions with \usage entries need to have the appropriate \alias
   entries, and all their arguments documented.
   The \usage entries must correspond to syntactically valid R code.
   See chapter ‘Writing R documen

> checking R files for non-ASCII characters ... WARNING
  Found the following file with non-ASCII characters:
    loadAboutTab.R
  Portable packages must use only ASCII characters in their R code,
  except perhaps in comments.
  Use \uxxxx escapes for other characters.

> checking Rd files ... WARNING
  checkRd: (7) launchApp.Rd:12: Tag \donttest not recognized
  checkRd: (7) plot3Dmodel.Rd:15-16: Tag \donttest not recognized

> checking Rd \usage sections ... WARNING
  Undocumented arguments in documentation object 'getDataValues'
    ‘tumor’ ‘tumorDatasetsPath’
  Documented arguments not in \usage in documentation object 'getDataValues':
    ‘sf’
  
  Undocumented arguments in documentation object 'plot3Dmodel'
    ‘tumorModelsPath’
  
  Functions with \usage entries need to have the appropriate \alias
  entries, and all their arguments documented.
  The \usage entries must correspond to syntactically valid R code.
  See chapter ‘Writing R documentation files’ in the ‘Writing R
  Extensions’ manual.
```

**Comment by HenrikBengtsson** [comment]
```
W  checking Rd files ...
   checkRd: (7) launchApp.Rd:12: Tag \donttest not recognized
   checkRd: (7) plot3Dmodel.Rd:15-16: Tag \donttest not recognized
```

Hmm... weird. Could it be that you're putting `\donttest{...}` outside of `\examples{}`?  It should be wrapped inside; look at your `man/launchApp.Rd` file.  Maybe it's easier if you push to GitHub so I can see there.

**Comment by SRHilz** [comment]
Ah okay thanks, yes, I had thought I needed it outside of examples. Moved it to inside and that warning went away (also pushed code to git). 

Now just left with the R files for non-ASCII and Rd \usage sections warnings.

**Comment by HenrikBengtsson** [comment]
I'll work on adding a GitHub Action template. I'll send it as a PR.

**Comment by HenrikBengtsson** [comment]
I've created PR #2.  Merge it and then look at the 'Actions' tab here on GitHub. I'll post separate issues related to the remaining WARNINGs and NOTEs.  You want your package to pass with all OKs.  Closing this one.
