### ISSUE TITLE
R CMD check --as-cran NOTE: Non-standard files/directories found at top level

### ISSUE THREAD

**Issue by HenrikBengtsson** [SRHilz/GliomaAtlas3D#11]
```
* checking top-level files ... NOTE
Non-standard files/directories found at top level:
  ‘LICENSE.md’ ‘depends.Rds’
```

I think the `LICENSE.md` file should be named just `LICENSE`.

What's the purpose of the `depends.Rds` file?

**Comment by SRHilz** [comment]
Okay, I can change it to LICENSE. And not sure what depends.Rds is - I am not seeing it in the package at all (just did a directory search), so not sure where the checker is finding it?

I wanted to see if this and the other issues are necessary to address before the app can run on our server? Or could we move forward with testing whether it will run on our server (which is urgent), and then I can address these issues, which seem to be more focused on ability to run the app on multiple platforms, over the next few weeks? Thanks!

**Comment by HenrikBengtsson** [comment]
> And not sure what depends.Rds is - I am not seeing it in the package at all (just did a directory search), so not sure where the checker is finding it?

Ah, it turns out to be [produced by the GitHub Actions workflow](https://github.com/SRHilz/GliomaAtlas3D/search?q=depends.Rds&unscoped_q=depends.Rds) and after now testing with the stricter `--as-cran`, it's revealed.  I'll fix that and let those who I got that template from know because that is a mistake.

**Comment by HenrikBengtsson** [comment]
... actually, I realized that the solution is probably to list `depends.Rds` in the `.Rbuildignore` file - I'll fix that and send another PR later.

**Comment by HenrikBengtsson** [comment]
If you want to keep `LICENSE.md`, we could add that to `.Rbuildignore` as well, but legally it is sufficient to specify it in the `DESCRIPTION` file + `LICENSE` as you do (without the extra `LICENSE.md` file).
