### ISSUE TITLE
TESTS: Add package test that produces a 3D plot using the 'rgl' package

### ISSUE THREAD

**Issue by HenrikBengtsson** [SRHilz/GliomaAtlas3D#15]
Per https://github.com/SRHilz/3DGliomaAtlas/issues/3#issuecomment-617439338, adding a package test that produces a 3D plot using the 'rgl' package will help make sure the package works in a headless environment.

@SRHilz, in `help("plot3dmodel")` there's the following example code snippet (that is currently disabled for running and testing):
```r
plot3Dmodel('Patient300','sf10711',rep('#FF0000',10))
```

If I try to run that, I get:
```r
> library(GliomaAtlas3D)
> plot3Dmodel('Patient300','sf10711',rep('#FF0000',10))
Error in paste0(tumorModelsPath, "/", patientID, "/", sf) : 
  argument "tumorModelsPath" is missing, with no default
```

What does it take to get a working example?

**Comment by SRHilz** [comment]
I see, okay, thank you for helping to sort this out.

And apologies that the example for plot3Dmodel was missing a key argument (I added this fourth argument --a path to the rds files specifying the tumor volume and sample coordinates -- later to fix one of our errors, and forgot to update the example). 

So what the example for plot3Dmodel should be is:

``
plot3Dmodel('Patient300','sf10711',rep('#FF0000',10), tumorModelsPath)
``

Where

``
tumorModelsPath <- "inst/exdata/models"
`` 

if we are working from the package directory itself.

Please let me know if that works, and thank you for looking into this.

**Comment by HenrikBengtsson** [comment]
FYI, when the package is installed, then the source folder `inst/exdata/` is available as:
```r
system.file(package = "GliomaAtlas3D", "exdata")
```

Because of this, I've set the default to `tumorModelsPath = system.file(package = "GliomaAtlas3D", "exdata", "models")`.
