### ISSUE TITLE
message() for method output - never print()

### ISSUE THREAD

**Issue by HenrikBengtsson** [SRHilz/GliomaAtlas3D#19]
You want to use `message()` to produce output for users in your functions.  Such output will end up on the standard error (stderr).  When you use `print()` it will end up on standard output (stdout).  It's common practice to output "progress" / "debug" messages to stderr.  The problem with outputting stdout is that if you run your function inside a vignette/Rmarkdown/Rnotebook/..., then such "progress" output will be captured and put inside the final document, which you rarely want to.

For example, if we run the test and redirect all stderr to `/dev/null`;
```sh
$ RGL_USE_NULL=true Rscript tests/plot3Dmodel.R 2> /dev/null
[1] "Creating brain contour and plotting brain"
[1] "Creating tumor contour and plotting tumor"
[1] "1"
[1] "2"
[1] "3"
[1] "4"
[1] "5"
[1] "6"
[1] "7"
[1] "8"
[1] "9"
[1] "10"
```
we see that there are 12 lines outputted to stdout.  These come from:

```sh
$ grep -F "print" R/*.R
R/plot3dSamples.R:      print(name)
R/plotTemplate.R:  print('Creating brain contour and plotting brain')
R/plotTemplate.R:  print('Creating tumor contour and plotting tumor')
```

**Comment by SRHilz** [comment]
Thank you, very helpful to know about message. I've fixed the issue in the latest push.
