### ISSUE TITLE
Shiny: Stray output at end of webpage

### ISSUE THREAD

**Issue by HenrikBengtsson** [SRHilz/GliomaAtlas3D#22]
There's stray output:
```
TRUE tab-2058-4
``` 
that ends up on all Shiny App webpages (http://cbi.ucsf.edu/apps/shinyproxy/app_direct/GliomaAtlas3D/).  

I suspect both come from R (especially since we have a `TRUE` in there).  It could be that they are from implicit `print()`:ing (for similar reasons as I mention in Issue #19) of these objects returned in some function in the Shiny UI/server code.  The solution could be to make sure to use `invisible()` when returning from the offending function(s), e.g. instead of
```r
foo <- function(...) {
  res <- TRUE
  res
}
```
use
```r
foo <- function(...) {
  res <- TRUE
  invisible(res)
}
```

**Comment by SRHilz** [comment]
I found a fix to this today (I had tried ```invisible()``` but was still getting the unwanted output). 

I had some extra content in ```navbarPage()``` in that was unnamed (see 
![image](https://user-images.githubusercontent.com/5839184/86500487-fd232f00-bd56-11ea-986e-95383f238b8c.png) for more details).

I transferred this content over from the main ```navbarPage()``` to dataTab ```tabPanel()```, which then results in “TRUE-tab-NNNN-N” no longer being output at bottom of each page.
