### ISSUE TITLE
Shiny: Display version

### ISSUE THREAD

**Issue by HenrikBengtsson** [SRHilz/GliomaAtlas3D#27]
I think it would be helpful if the Shiny UI would reveal the version of the package in some location/on some tab This would allow you to go to http://cbi.ucsf.edu/apps/shinyproxy/app/GliomaAtlas3D and tell if it is running the version you expect.

To get the version of a package, use:
```r
> version <- packageVersion("GliomaAtlas3D")
> version
[1] '0.0.0'
> as.character(version)
[1] "0.0.0"
```

PS. When you put this inside the package, you can use `packageVersion(.packageName)` which has the (only) advantage of being agile to package name changes, if you for some reason end up changing the name.  It's just a trick to be aware.

**Comment by SRHilz** [comment]
This is a great idea, thank you for suggesting and providing the tips on how to do it. Just added a print to the about page that will show the version info of .packageName. Pushed the changes here and also to docker, so will now confirm we see the reflected changes on the server. 
<img width="1128" alt="Screen Shot 2020-06-04 at 2 40 32 PM" src="https://user-images.githubusercontent.com/5839184/83813672-a997c580-a672-11ea-9a60-642e16aed80b.png">
