### ISSUE TITLE
Add NEWS file

### ISSUE THREAD

**Issue by HenrikBengtsson** [SRHilz/GliomaAtlas3D#28]
Since this package and the Shiny app is more or less public, I think it's a good time to add a NEWS file describing what had changed. This also bring up the need for bumping the package version.

**Comment by SRHilz** [comment]
Great idea - I will try making a NEWS file this week. And having a package version would also be wonderful. Is there a package/tool in R or git that helps with managing versions? Thanks!

**Comment by HenrikBengtsson** [comment]
Bumping version is a manual process. You just update the `Version` field in the DESCRIPTION file.  I find [semantic versioning](https://semver.org/) to work fairly well for me.  You don't have to follow it strictly but it helps you to decide how to bump x.y.z versions.  For instance, if there are only bug fixes, then I bump to x.y.{z+1}.   If I add new features, e.g. a new function, a new data set, a new argument, then I bump to x.{y+1}.0.   If I make really big changes that are likely to be disruptive for people, which is really rare for me, then I bump to {x+1}.0.0.

---

For the NEWS file, I typically categorize news entries into a few major subsections:

* Significant Changes - major improvements you want people to be aware of
* New Features - new functions, new arguments, new data sets
* Bug Fixes

NEWS entries should be in reverse chronicle order so that the most recent updates are on top.

As an example, here's one of my NEWS files: https://github.com/HenrikBengtsson/future/blob/develop/NEWS

---- 

Releasing new versions:  For work in progress, aka development version, a common standard in R is to append `.9000` or `-9000` to the last released version x.y.z.  For instance, if you previously released 0.1.1.  Then the code under development is 0.1.1-9000.   This signals to others that whatever is under development might be broken and things might have been updated since you last downloaded it.  I don't bump my development version while developing.

When I find my development version stable, well tested and I think it is worth sharing with the world, then I freeze the code and do no more commits.  I bump the development version to a release version, e.g. 0.1.1-9000 -> 0.2.0.  I make sure that this version number is used in DESCRIPTION and the NEWS file.  Then I commit and push to the master branch.  I also do a:

```
$ git tag 0.2.0
$ git push --tags
```

This way it will be easy to find old versions in the git history. GitHub will also display these online.

After this, I immediately bump the development version in DESCRIPTION and the NEWS file, so there is no risk that someone who installs the development version sees the same version number as the latest release.

**Comment by SRHilz** [comment]
This is so helpful, thank you!
