### ISSUE TITLE
GitHub link in Shiny App

### ISSUE THREAD

**Issue by HenrikBengtsson** [SRHilz/GliomaAtlas3D#30]
I'd like to suggest adding a link to this https://github.com/SRHilz/GliomaAtlas3D repository inside the Shiny App, e.g. by updating "Currently running version 0.1.0" to "[GliomaAtlas3D 0.1.0](https://github.com/SRHilz/GliomaAtlas3D)".   Alternative, or in addition, this could be added to the 'Download' tab (not sure if that's meant for downloading data or the app itself).

PS. Don't forget to update/push to Docker Hub in order for the online app to be updated.

**Comment by SRHilz** [comment]
Good idea, added to the latest update, which I just finished and pushed to Docker Hub. Thanks!
