### ISSUE TITLE
Bump to develop version

### ISSUE THREAD

**Issue by HenrikBengtsson** [SRHilz/GliomaAtlas3D#34]
I use version suffix `-9000` to indicate a developer version.  For example, when I release a new version, I bump it to a new x.y.z version number, e.g. `0.1.0`.  Then I tag that commit as `git tag 0.1.0`, which will make it appear under 'releases' on GitHub, e.g. https://github.com/SRHilz/GliomaAtlas3D/releases.  I then immediately bump the develop version to `0.1.0-9000` (which I don't tag) and do another commit.   This way there is only exactly one release of `0.1.0`, which can be installed as:

```r
remotes::install_github("SRHilz/GliomaAtlas3D", ref="0.1.0")
```
whereas the development version is installed as:
```r
remotes::install_github("SRHilz/GliomaAtlas3D")
```

Point is, you don't want to keep commit to stable versions that have been released.  If someone reports they have an issue with version 0.1.0 you want to that to mean they run an explicit commit.  If they report they have problems with 0.1.0-9000, then you both know it's a developers version and you need to sync more carefully what commit the problem occurs with.

**Comment by SRHilz** [comment]
This is very helpful to know, thanks! I will start doing this from here on out.
