### ISSUE TITLE
Missing LICENSE file required by the MIT license

### ISSUE THREAD

**Issue by HenrikBengtsson** [SRHilz/GliomaAtlas3D#5]
See GitHub Actions, `R CMD check --as-cran` reports on:
```r
* checking DESCRIPTION meta-information ... NOTE
License components which are templates and need '+ file LICENSE':
  MIT
```

When using the MIT license, you need to accompany with a `LICENSE` file in order for the license to be valid.  See https://github.com/r-lib/crayon for an example.

**Comment by SRHilz** [comment]
Fixed this by running:

usethis::use_mit_license("Stephanie Hilz")

Which created a LICENSE file like the one in the example (I tried making it myself first, but it was still giving me the error, so this seemed to help get me past it).

Thanks!
