### ISSUE TITLE
checking R files for non-ASCII characters ... WARNING

### ISSUE THREAD

**Issue by HenrikBengtsson** [SRHilz/GliomaAtlas3D#6]
See GitHub Actions, `R CMD check --as-cran` reports on:

```r
* checking R files for non-ASCII characters ... WARNING
##[warning]Found the following file with non-ASCII characters:
  loadAboutTab.R
Portable packages must use only ASCII characters in their R code,
except perhaps in comments.
Use \uxxxx escapes for other characters.
```

I forgot exactly how to fix this, but I'll look into it.

**Comment by HenrikBengtsson** [comment]
The R `tools` package has a function to give details on this.  It reports:

```r
> tools::showNonASCIIfile("R/loadAboutTab.R")
34:                p("To create the 3D Glioma Atlas, we maximally sampled the
anatomical diversity present in each patient<e2><80><99>s tumor, registering the
physical location of each sample to a preoperative magnetic resonance image (MRI).
This allowed us to analyze genomic and histologic information from each sample in
relation to other samples and the tumor as a whole."),
```

So, it looks like a simple fix.  You just happen to have a "funny" single quote in your "... patient's ..." - probably just from cut'n'pasting from some webpage or similar.  Replace that with a basic single quote should fix this WARNING.

**Comment by SRHilz** [comment]
Thanks! Fixed and then confirmed with devtools::check() that this eliminated this warning.
