### ISSUE TITLE
Warning: 'rgl.init' failed, running with 'rgl.useNULL = TRUE'

### ISSUE THREAD

**Issue by HenrikBengtsson** [SRHilz/GliomaAtlas3D#7]
See GitHub Actions, `R CMD check --as-cran` reports on:
```r
* checking whether package ‘GliomaAtlas3D’ can be installed ... WARNING
##[warning]Found the following significant warnings:
  Warning: 'rgl.init' failed, running with 'rgl.useNULL = TRUE'.
See ‘/home/runner/work/GliomaAtlas3D/GliomaAtlas3D/check/GliomaAtlas3D.Rcheck/00install.out’ for details.
```

This is a trickier one.  It is most likely related to the fact that the machine where the checks are running does not have windows manager running, i.e. it's a "head-less server".  It can be fixed and should be fixed.  I'll look into this one.

**Comment by SRHilz** [comment]
Have you been able to look into this one yet? Here is a discussion I found about it https://github.com/r-lib/remotes/issues/332

I've gotten through all of the other issues (thanks for all of the pointers on what direction to take with each), so I think this is the last one we need to troubleshoot.

**Comment by HenrikBengtsson** [comment]
I'm working on it, but see the PR I've sent.  It's waiting to get merged.

**Comment by SRHilz** [comment]
Whoops, apologies for not seeing that merge request. Accepted. Let me know if that was all I needed to do. Thanks!

**Comment by pat-s** [comment]
Regarding the {rgl} issues:

- Add `brew cask install xquartz`
- Set env var `DISPLAY` to `:99` in the respective stage, e.g. `export DISPLAY=:99`
- Setting `RGL_USE_NULL = true` suppresses the additional warning which is usually issued but is just optional and does not help the install to pass.

See https://github.com/ropenscilabs/tic.package/runs/582925992.

**Comment by HenrikBengtsson** [comment]
@pat-s, thxs a bunch - this fixed it for us.  Figuring out how to install xquartz on a macOS and then also figuring out that `DISPLAY` needed to be set while running R CMD check would have taken lots of trial and errors before I would have figured that one out (especially since I don't have access to a macOS).

**Comment by SRHilz** [comment]
Thanks all!
